### ISSUE TITLE
Possible missing translation

### ISSUE THREAD

**Issue by PanPraescribens** [anegostudios/vssurvivalmod#13]
https://github.com/anegostudios/vssurvivalmod/blob/8d22d51e04fa0cc07eb693edfd5a753711143247/BlockEntity/BlockEntityGroundStorage.cs#L884

I'm actually looking for the *contents description* string of the ground storage, which Chinese user Law_4x showed had a missing " in ". e.g. "Rot in pot", the "in" is still there in Chinese. 
Not sure where it could be as I don't see anything here.

**Comment by tyronx** [comment]
I could have sworn i fixed this. will do, thanks for the report.
