### ISSUE TITLE
Translation refered in code but missing in en.json

### ISSUE THREAD

**Issue by PanPraescribens** [anegostudios/vssurvivalmod#14]
https://github.com/anegostudios/vssurvivalmod/blob/9f2f42da65ac74d1aff50f480c6c38769c87890a/Block/BlockCookedContainerBase.cs#L347

As brought up by user Law_4x, the in is not being translated correctly. I checked in en.json and there is no " in {0}" entry.

**Comment by tyronx** [comment]
thanks for the report, this should be fixed in 1.18
