### ISSUE TITLE
Terrain generation error in worlds 1024 by 1024

### ISSUE THREAD

**Issue by VeryGoodDog** [anegostudios/vssurvivalmod#3]
When generating a new world, making the world size 1024 causes a large discontinuity in the northeast quadrant from spawn.
![image](https://user-images.githubusercontent.com/22282562/77571368-a11d5480-6ea3-11ea-9966-f707802091f8.png)
I tested with worlds 384, 1024, 5120, 10240, 60000, and 1024000. Only worlds of 1024 size showed this bug.
I also tested 1024 worlds with one seed in .12.9-rc.1 and .12.11 which both displayed the same bug. I used this seed to test the other sized worlds. In .12.11 a different seed for a 1024 world showed the same bug.

System Specs:
Model Identifier: MacBookPro11,3
Processor Name: Quad-Core Intel Core i7
Processor Speed: 2.6 GHz
Memory: 16 GB
macOS: 10.15.3 (19D76)
Mono: 6.6.0.166

lmk if you need the world files.

**Comment by tyronx** [comment]
thank you, should be fixed in v1.12.12
