### ISSUE TITLE
No return in BlockWateringCan.cs when refilling from bucket

### ISSUE THREAD

**Issue by Maldaris** [anegostudios/vssurvivalmod#4]
`Block\BlockWateringCan.cs` after Line 68 is missing a return statement. 

In the code block above, the refill process returns after refilling from a water sourceblock and setting `handHandling = EnumHandHandling.PreventDefault;` The `ItemStack.TempAttributes` flag `refilled` is set to `1`, then immediately `0` afterwards, and the watering loop callback `After350ms` is registered, triggering sound on the bucket, even though it's not watered in the `OnHeldInteractStep` function.

**Comment by tyronx** [comment]
thanks, i have fixed this now, will be in pre.3
